In [110]:
from babel.localedata import merge
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from oauthlib.uri_validate import query
from sympy import sequence

In [111]:
from dotenv import load_dotenv
load_dotenv()

True

In [112]:
import pandas as pd
books=pd.read_csv('books_cleaned.csv')

In [113]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,199,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,205,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,57,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,45,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,75,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [114]:
books["tagged_description"].to_csv('tagged_description.txt', index=False, header=False, encoding='utf-8')

In [115]:
raw_documents = TextLoader("tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 0
Created a chunk of size 1216, which is longer than the specified 0
Created a chunk of size 375, which is longer than the specified 0
Created a chunk of size 311, which is longer than the specified 0
Created a chunk of size 483, which is longer than the specified 0
Created a chunk of size 484, which is longer than the specified 0
Created a chunk of size 962, which is longer than the specified 0
Created a chunk of size 188, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 296, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 881, which is longer than the specified 0
Created a chunk of size 1090, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 270, which is longer than the specified 0
Created a chunk of size 213, which is longer than the specified 0
Created a chunk of size 216, which is longer than the specified 0
Created a chunk of size 515, which is longer than the specified 0
Created a chunk of size 754, which is longer than the specified 0
Created a chunk of size 390, which is longer than the specified 0
Created a chunk of size 265, which is longer than the specified 0
Created a chunk of size 253, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 730, which is longer than the specified 0
Created a chunk of size 723, which is longer than the specified 0
Created a chunk of size 258, which is longer than the specified 0
Created a chunk of size 475, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 1267, which is longer than the specified 0
Created a chunk of size 683, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 555, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 282, which is longer than the specified 0
Created a chunk of size 789, which is longer than the specified 0
Created a chunk of size 566, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 179, which is longer than the specified 0
Created a chunk of size 299, which is longer than the specified 0
Created a chunk of size 535, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 565, which is longer than the specified 0
Created a chunk of size 385, which is longer than the specified 0
Created a chunk of size 412, which is longer than the specified 0
Created a chunk of size 463, which is longer than the specified 0
Created a chunk of size 597, which is longer than the specified 0
Created a chunk of size 478, which is longer than the specified 0
Created a chunk of size 461, which is longer than the specified 0
Created a chunk of size 259, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 616, which is longer than the specified 0
Created a chunk of size 421, which is longer than the specified 0
Created a chunk of size 889, which is longer than the specified 0
Created a chunk of size 695, which is longer than the specified 0
Created a chunk of size 304, which is longer than the specified 0
Created a chunk of size 219, which is longer than the specified 0
Created a chunk of size 277, which is longer than the specified 0
Created a chunk of size 2010, which is longer than the specified 0
Created a chunk of size 175, which is longer than the specified 0
Created a chunk of size 481, which is longer than the specified 0
Created a chunk of size 302, which is longer than the specified 0
Created a chunk of size 522, which is longer than the specified 0
Created a chunk of size 649, which is longer than the specified 0
Created a chunk of size 778, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 688, which is longer than the specified 0
Created a chunk of size 550, which is longer than the specified 0
Created a chunk of size 1225, which is longer than the specified 0
Created a chunk of size 408, which is longer than the specified 0
Created a chunk of size 1186, which is longer than the specified 0
Created a chunk of size 1216, which is longer than the specified 0
Created a chunk of size 1193, which is longer than the specified 0
Created a chunk of size 1059, which is longer than the specified 0
Created a chunk of size 246, which is longer than the specified 0
Created a chunk of size 690, which is longer than the specified 0
Created a chunk of size 878, which is longer than the specified 0
Created a chunk of size 286, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 389, which is longer than the specified 0
Created a chunk of size 419, which is longer than the specified 0
Created a chunk of size 210, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 725, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 163, which is longer than the specified 0
Created a chunk of size 528, which is longer than the specified 0
Created a chunk of size 523, which is longer than the specified 0
Created a chunk of size 214, which is longer than the specified 0
Created a chunk of size 340, which is longer than the specified 0
Created a chunk of size 901, which is longer than the specified 0
Created a chunk of size 1272, which is longer than the specified 0
Created a chunk of size 560, which is longer than the specified 0
Created a chunk of size 1637, which is longer than the specified 0
Created a chunk of size 438, which is longer than the specified 0
Created a chunk of size 251, which is longer than the specified 0
Created a chunk of size 779, which is longer than the specified 0
Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 516, which is longer than the specified 0
Created a chunk of size 960, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1132, which is longer than the specified 0
Created a chunk of size 170, which is longer than the specified 0
Created a chunk of size 1325, which is longer than the specified 0
Created a chunk of size 853, which is longer than the specified 0
Created a chunk of size 272, which is longer than the specified 0
Created a chunk of size 801, which is longer than the specified 0
Created a chunk of size 1121, which is longer than the specified 0
Created a chunk of size 838, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 734, which is longer than the specified 0
Created a chunk of size 1195, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 775, which is longer than the specified 0
Created a chunk of size 280, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 358, which is longer than the specified 0
Created a chunk of size 768, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 718, which is longer than the specified 0
Created a chunk of size 2012, which is longer than the specified 0
Created a chunk of size 308, which is longer than the specified 0
Created a chunk of size 1288, which is longer than the specified 0
Created a chunk of size 1231, which is longer than the specified 0
Created a chunk of size 729, which is longer than the specified 0
Created a chunk of size 750, which is longer than the specified 0
Created a chunk of size 447, which is longer than the specified 0
Created a chunk of size 1242, which is longer than the specified 0
Created a chunk of size 311, which is longer than the specified 0
Created a chunk of size 914, which is longer than the specified 0
Created a chunk of size 306, which is longer than the specified 0
Created a chunk of size 846, which is longer than the specified 0
Created a chunk of size 1128, which is longer than the specified 0
Created a chunk of size 1075, which is longer than the specified 0
Created a chunk of size 1320, which is longer than the specified 0
Created a chunk of size 363, which is longer than the specified 0
Created a chunk of size 2834, which is longer than the specified 0
Created a chunk of size 237, which is longer than the specified 0
Created a chunk of size 242, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 572, which is longer than the specified 0
Created a chunk of size 208, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 1006, which is longer than the specified 0
Created a chunk of size 715, which is longer than the specified 0
Created a chunk of size 712, which is longer than the specified 0
Created a chunk of size 2510, which is longer than the specified 0
Created a chunk of size 956, which is longer than the specified 0
Created a chunk of size 309, which is longer than the specified 0
Created a chunk of size 351, which is longer than the specified 0
Created a chunk of size 641, which is longer than the specified 0
Created a chunk of size 405, which is longer than the specified 0
Created a chunk of size 525, which is longer than the specified 0
Created a chunk of size 795, which is longer than the specified 0
Created a chunk of size 167, which is longer than the specified 0
Created a chunk of size 391, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 1424, which is longer than the specified 0
Created a chunk of size 1085, which is longer than the specified 0
Created a chunk of size 1146, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 790, which is longer than the specified 0
Created a chunk of size 297, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 256, which is longer than the specified 0
Created a chunk of size 876, which is longer than the specified 0
Created a chunk of size 808, which is longer than the specified 0
Created a chunk of size 1814, which is longer than the specified 0
Created a chunk of size 1830, which is longer than the specified 0
Created a chunk of size 1064, which is longer than the specified 0
Created a chunk of size 955, which is longer than the specified 0
Created a chunk of size 1182, which is longer than the specified 0
Created a chunk of size 283, which is longer than the specified 0
Created a chunk of size 283, which is longer than the specified 0
Created a chunk of size 288, which is longer than the specified 0
Created a chunk of size 1286, which is longer than the specified 0
Created a chunk of size 1644, which is longer than the specified 0
Created a chunk of size 759, which is longer than the specified 0
Created a chunk of size 1932, which is longer than the specified 0
Created a chunk of size 874, which is longer than the specified 0
Created a chunk of size 2008, which is longer than the specified 0
Created a chunk of size 2285, which is longer than the specified 0
Created a chunk of size 173, which is longer than the specified 0
Created a chunk of size 1003, which is longer than the specified 0
Created a chunk of size 579, which is longer than the specified 0
Created a chunk of size 290, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 1144, which is longer than the specified 0
Created a chunk of size 559, which is longer than the specified 0
Created a chunk of size 1143, which is longer than the specified 0
Created a chunk of size 245, which is longer than the specified 0
Created a chunk of size 1088, which is longer than the specified 0
Created a chunk of size 1483, which is longer than the specified 0
Created a chunk of size 223, which is longer than the specified 0
Created a chunk of size 1137, which is longer than the specified 0
Created a chunk of size 724, which is longer than the specified 0
Created a chunk of size 668, which is longer than the specified 0
Created a chunk of size 767, which is longer than the specified 0
Created a chunk of size 608, which is longer than the specified 0
Created a chunk of size 572, which is longer than the specified 0
Created a chunk of size 967, which is longer than the specified 0
Created a chunk of size 859, which is longer than the specified 0
Created a chunk of size 1034, which is longer than the specified 0
Created a chunk of size 191, which is longer than the specified 0
Created a chunk of size 367, which is longer than the specified 0
Created a chunk of size 497, which is longer than the specified 0
Created a chunk of size 652, which is longer than the specified 0
Created a chunk of size 350, which is longer than the specified 0
Created a chunk of size 735, which is longer than the specified 0
Created a chunk of size 527, which is longer than the specified 0
Created a chunk of size 1017, which is longer than the specified 0
Created a chunk of size 972, which is longer than the specified 0
Created a chunk of size 206, which is longer than the specified 0
Created a chunk of size 690, which is longer than the specified 0
Created a chunk of size 546, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 209, which is longer than the specified 0
Created a chunk of size 378, which is longer than the specified 0
Created a chunk of size 933, which is longer than the specified 0
Created a chunk of size 564, which is longer than the specified 0
Created a chunk of size 856, which is longer than the specified 0
Created a chunk of size 717, which is longer than the specified 0
Created a chunk of size 749, which is longer than the specified 0
Created a chunk of size 714, which is longer than the specified 0
Created a chunk of size 326, which is longer than the specified 0
Created a chunk of size 243, which is longer than the specified 0
Created a chunk of size 1090, which is longer than the specified 0
Created a chunk of size 725, which is longer than the specified 0
Created a chunk of size 247, which is longer than the specified 0
Created a chunk of size 229, which is longer than the specified 0
Created a chunk of size 706, which is longer than the specified 0
Created a chunk of size 1914, which is longer than the specified 0
Created a chunk of size 397, which is longer than the specified 0
Created a chunk of size 487, which is longer than the specified 0
Created a chunk of size 622, which is longer than the specified 0
Created a chunk of size 561, which is longer than the specified 0
Created a chunk of size 558, which is longer than the specified 0
Created a chunk of size 388, which is longer than the specified 0
Created a chunk of size 231, which is longer than the specified 0
Created a chunk of size 427, which is longer than the specified 0
Created a chunk of size 418, which is longer than the specified 0
Created a chunk of size 284, which is longer than the specified 0
Created a chunk of size 168, which is longer than the specified 0
Created a chunk of size 626, which is longer than the specified 0
Created a chunk of size 2616, which is longer than the specified 0
Created a chunk of size 1580, which is longer than the specified 0
Created a chunk of size 391, which is longer than the specified 0
Created a chunk of size 996, which is longer than the specified 0
Created a chunk of size 849, which is longer than the specified 0
Created a chunk of size 265, which is longer than the specified 0
Created a chunk of size 338, which is longer than the specified 0
Created a chunk of size 1530, which is longer than the specified 0
Created a chunk of size 215, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 2032, which is longer than the specified 0
Created a chunk of size 398, which is longer than the specified 0
Created a chunk of size 1619, which is longer than the specified 0
Created a chunk of size 700, which is longer than the specified 0
Created a chunk of size 824, which is longer than the specified 0
Created a chunk of size 356, which is longer than the specified 0
Created a chunk of size 843, which is longer than the specified 0
Created a chunk of size 1191, which is longer than the specified 0
Created a chunk of size 197, which is longer than the specified 0
Created a chunk of size 510, which is longer than the specified 0
Created a chunk of size 665, which is longer than the specified 0
Created a chunk of size 1284, which is longer than the specified 0
Created a chunk of size 262, which is longer than the specified 0
Created a chunk of size 244, which is longer than the specified 0
Created a chunk of size 217, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1268, which is longer than the specified 0
Created a chunk of size 1277, which is longer than the specified 0
Created a chunk of size 200, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0
Created a chunk of size 380, which is longer than the specified 0
Created a chunk of size 271, which is longer than the specified 0
Created a chunk of size 179, which is longer than the specified 0
Created a chunk of size 227, which is longer than the specified 0
Created a chunk of size 224, which is longer than the specified 0
Created a chunk of size 784, which is longer than the specified 0
Created a chunk of size 971, which is longer than the specified 0
Created a chunk of size 615, which is longer than the specified 0
Created a chunk of size 165, which is longer than the specified 0
Created a chunk of size 759, which is longer than the specified 0
Created a chunk of size 291, which is longer than the specified 0
Created a chunk of size 247, which is longer than the specified 0
Created a chunk of size 965, which is longer than the specified 0
Created a chunk of size 234, which is longer than the specified 0
Created a chunk of size 845, which is longer than the specified 0
Created a chunk of size 788, which is longer than the specified 0
Created a chunk of size 650, which is longer than the specified 0
Created a chunk of size 986, which is longer than the specified 0
Created a chunk of size 799, which is longer than the specified 0
Created a chunk of size 193, which is longer than the specified 0
Created a chunk of size 1163, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 203, which is longer than the specified 0
Created a chunk of size 1058, which is longer than the specified 0

In [116]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [117]:
db_books=Chroma.from_documents(documents,embedding=OpenAIEmbeddings())

In [118]:
query="A book to teach children about nature"
docs=db_books.similarity_search(query,k=10)
docs

[Document(id='be1690af-4ae3-49fa-be72-b15c66a769d9', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='d89d059d-b1e5-47f5-8e4c-a50d3e08200b', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='5cdaa37c-2ded-4f9c-a912-f42529ceda7f', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(id='4ff01fa5-ff28-4436-b956-6c58948689dd', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='a45b7ccc-0f61-4171-b49d-95a10051f2da', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='ee350e07-3abe-42b0-8d93-04637a4778a2', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='51e22fe1-5a30-4773-b5fa-7672052ef3b7', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='4a408534-e7ca-4dbd-adda-b4c40882948e', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='e08c9903-0163-4cff-961f-7e0f4c0d036a', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(id='41dff899-2147-425a-8f77-250990f59a20', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."')]

In [119]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip().strip('"'))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,40,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [120]:
def retrieve_schematic_recommendations(query: str, top_k: int = 10) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)
    books_list = []

    for i in range(len(recs)):
        isbn_str = recs[i].page_content.strip('"').split()[0].strip()
        try:
            books_list.append(int(isbn_str))
        except ValueError:
            continue

    return books[books["isbn13"].isin(books_list)].head(top_k)

In [121]:
retrieve_schematic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,39,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,322,The Sense of Wonder,9780067575208 First published more than three ...
1078,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,340101.0,28,The Very Hungry Caterpillar,9780241003008 Eric Carle's children's classic ...
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,44,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
2201,9780440362050,0440362059,My Name is Aram,William Saroyan,Fiction,http://books.google.com/books/content?id=2P3XA...,A small boy finds excitement and promise in th...,1966.0,4.15,151.0,975.0,29,My Name is Aram,9780440362050 A small boy finds excitement and...
3214,9780689861130,0689861133,"Moo, Baa, la la La!",Sandra Boynton,Animal sounds,http://books.google.com/books/content?id=Gz40A...,Children will love joining in and imitating th...,2004.0,4.20,14.0,28261.0,27,"Moo, Baa, la la La!",9780689861130 Children will love joining in an...
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,34,Judy Moody Saves the World!,9780763620875 When Judy Moody gets serious abo...
3591,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,70,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781 Titles in this series present ba...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,40,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,64,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."

In [122]:
books["categories"].value_counts().reset_index()

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
..                          ...    ...
474  Human-animal relationships      1
475                 Imperialism      1
476                  Aged women      1
477            Humorous stories      1
478                     Butlers      1

[479 rows x 2 columns]

In [123]:
books["categories"].value_counts().reset_index().query("count > 50")

                   categories  count
0                     Fiction   2111
1            Juvenile Fiction    390
2   Biography & Autobiography    311
3                     History    207
4          Literary Criticism    124
5                    Religion    117
6                  Philosophy    117
7     Comics & Graphic Novels    116
8                       Drama     86
9         Juvenile Nonfiction     57
10                    Science     56
11                     Poetry     51

In [124]:
category_mapping = {
    'Fiction': "This is a fictional story",
    'Juvenile Fiction': "This is a children's fictional story",
    'Biography & Autobiography': "This is a nonfiction book",
    'History': "This is a nonfiction book",
    'Literary Criticism': "This is a nonfiction book",
    'Philosophy': "This is a nonfiction book",
    'Religion': "This is a nonfiction book",
    'Comics & Graphic Novels': "This is a fictional story",
    'Drama': "This is a fictional story",
    'Juvenile Nonfiction': "This is a children's nonfiction book",
    'Science': "This is a nonfiction book",
    'Poetry': "This is a fictional story"
}
books["simple_categories"] = books["categories"].map(category_mapping)

In [125]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,199,Gilead,9780002005883 A NOVEL THAT READERS and critics...,This is a fictional story
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,205,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,57,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",This is a fictional story
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,45,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,75,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,288,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,63,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,117,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,174,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,This is a nonfiction book
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,245,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,This is a nonfiction book

In [126]:
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,199,Gilead,9780002005883 A NOVEL THAT READERS and critics...,This is a fictional story
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,57,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",This is a fictional story
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,136,Warhost of Vastmark,9780006482079 Tricked once more by his wily ha...,This is a fictional story
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,129,Ocean Star Express,9780006646006 Joe and his parents are enjoying...,This is a children's fictional story
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,100,Taken at the Flood,9780007121014 A Few Weeks After Marrying An At...,This is a fictional story
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,100,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels defin...",This is a fictional story
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,41,Coin Locker Babies,9784770028969 Rescued from the lockers in whic...,This is a fictional story
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,33,"Cry, the Peacock",9788122200850 This book is the story of a youn...,This is a fictional story
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,174,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,This is a nonfiction book
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,245,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,This is a nonfiction book

In [144]:
from transformers import pipeline

fiction_categories = ["This is a fictional story", "This is a nonfiction book"]

pipe = pipeline("zero-shot-classification", model="MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli")

C:\Users\salah\PycharmProjects\Book-Recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\salah\.cache\huggingface\hub\models--MoritzLaurer--DeBERTa-v3-base-mnli-fever-anli. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Device set to use cpu

In [145]:
sequence=books.loc[books["simple_categories"]=="This is a fictional story","description"].reset_index(drop=True)[0]

In [146]:
sequence

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [147]:
pipe(sequence,fiction_categories)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['This is a fictional story', 'This is a nonfiction book'],
 'scores': [0.9983216524124146, 0.0016783169703558087]}

In [148]:
import numpy as np

max_index=np.argmax(pipe(sequence,fiction_categories)["scores"])
max_label=pipe(sequence,fiction_categories)["labels"][max_index]
max_label

'This is a fictional story'

In [149]:
def generate_prediction(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [150]:
from tqdm import tqdm

actual_cat=[]
predicted_cat=[]

for i in tqdm(range(0,300)):
    sequence=books.loc[books["simple_categories"]=="This is a fictional story","description"].reset_index(drop=True)[i]
    predicted_cat+=[generate_prediction(sequence, fiction_categories)]
    actual_cat+=["This is a fictional story"]

100%|██████████| 300/300 [03:54<00:00,  1.28it/s]

In [151]:
for i in tqdm(range(0,300)):
    sequence=books.loc[books["simple_categories"]=="This is a nonfiction book","description"].reset_index(drop=True)[i]
    predicted_cat+=[generate_prediction(sequence, fiction_categories)]
    actual_cat+=["This is a nonfiction book"]

100%|██████████| 300/300 [03:54<00:00,  1.28it/s]

In [152]:
prediction_df=pd.DataFrame({"actual_cat":actual_cat,"predicted_cat":predicted_cat})

In [153]:
prediction_df

                    actual_cat              predicted_cat
0    This is a fictional story  This is a fictional story
1    This is a fictional story  This is a fictional story
2    This is a fictional story  This is a fictional story
3    This is a fictional story  This is a fictional story
4    This is a fictional story  This is a fictional story
..                         ...                        ...
595  This is a nonfiction book  This is a fictional story
596  This is a nonfiction book  This is a fictional story
597  This is a nonfiction book  This is a fictional story
598  This is a nonfiction book  This is a nonfiction book
599  This is a nonfiction book  This is a fictional story

[600 rows x 2 columns]

In [154]:
prediction_df = pd.DataFrame({
    "actual": actual_cat,
    "predicted": predicted_cat
})
prediction_df["correct"] = (prediction_df["actual"] == prediction_df["predicted"]).astype(int)

accuracy = prediction_df["correct"].mean()
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 80.17%

In [155]:
prediction_df["correct"].sum()/len(prediction_df)

np.float64(0.8016666666666666)

In [156]:
isbns=[]
predicted_cats=[]

missing_cats= books.loc[books["simple_categories"].isna(),["isbn13","description"]].reset_index(drop=True)

In [159]:
missing_cats

             isbn13                                        description
0     9780002261982  A new 'Christie for Christmas' -- a full-lengt...
1     9780006280897  Lewis' work on the nature of love divides love...
2     9780006280934  "In The Problem of Pain, C.S. Lewis, one of th...
3     9780006380832  Until Vasco da Gama discovered the sea-route t...
4     9780006470229  A new-cover reissue of the fourth book in the ...
...             ...                                                ...
1449  9788125026600  Not only does Nietzsche for Beginners delve in...
1450  9788171565641  Forster's lively, informed originality and wit...
1451  9788172235222  On A Train Journey Home To North India After L...
1452  9788173031014  This book tells the tale of a man who goes on ...
1453  9788179921623  Wisdom to Create a Life of Passion, Purpose, a...

[1454 rows x 2 columns]

In [165]:
for i in tqdm(range(0,len(missing_cats))):
    sequence=missing_cats["description"][i]
    predicted_cats+=[generate_prediction(sequence, fiction_categories)]
    isbns += [missing_cats["isbn13"][i]]

100%|██████████| 1454/1454 [15:20<00:00,  1.58it/s]

In [166]:
missing_predicted_df=pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [167]:
missing_predicted_df

             isbn13       predicted_categories
0     9780002261982  This is a fictional story
1     9780006280897  This is a fictional story
2     9780006280934  This is a nonfiction book
3     9780006380832  This is a fictional story
4     9780006470229  This is a fictional story
...             ...                        ...
1449  9788125026600  This is a nonfiction book
1450  9788171565641  This is a fictional story
1451  9788172235222  This is a fictional story
1452  9788173031014  This is a fictional story
1453  9788179921623  This is a fictional story

[1454 rows x 2 columns]

In [168]:
books=pd.merge(books,missing_predicted_df,how="left",on="isbn13")
books["simple_categories"]=np.where(books["simple_categories"].isna(),books["predicted_categories"],books["simple_categories"])
books=books.drop(columns=["predicted_categories"])

In [169]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,199,Gilead,9780002005883 A NOVEL THAT READERS and critics...,This is a fictional story
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,205,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,This is a fictional story
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,57,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",This is a fictional story
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,45,The Four Loves,9780006280897 Lewis' work on the nature of lov...,This is a fictional story
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,75,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",This is a nonfiction book
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,288,Mistaken Identity,9788172235222 On A Train Journey Home To North...,This is a fictional story
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,63,Journey to the East,9788173031014 This book tells the tale of a ma...,This is a fictional story
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,117,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,This is a fictional story
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,174,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,This is a nonfiction book
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,245,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,This is a nonfiction book

In [170]:
books[books["categories"].str.lower().isin([
    "romance",
    "science fiction",
    "scifi",
    "fantasy",
    "horror",
    "mystery",
    "thriller",
    "comedy",
    "crime",
    "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,words_by_count,title_and_subtitle,tagged_description,simple_categories
24,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,119,Gravity,9780006513087 Emma Watson a research physician...,This is a fictional story
475,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,175,Traitor,"9780099410355 From the depths of catastrophe, ...",This is a fictional story
478,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,50,Yeats is Dead!: A Novel by Fifteen Irish Writers,"9780099422341 In aid of Amnesty International,...",This is a fictional story
491,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,186,Blackwood Farm,"9780099446729 Lestat Is Back, Saviour And Demo...",This is a fictional story
1090,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,33,The Silmarillion,9780261102422 Tolkien's Silmarillion is the co...,This is a fictional story
1435,9780340837955,0340837950,Stranger in a Strange Land,Robert A. Heinlein,Science fiction,http://books.google.com/books/content?id=ZQhiP...,"Epic, entertaining, Stranger in a Strange Land...",2005.0,3.92,672.0,563.0,58,Stranger in a Strange Land,"9780340837955 Epic, entertaining, Stranger in ...",This is a fictional story
1439,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,30,Visions from Nowhere,"9780345251220 The first novel in the series, ""...",This is a fictional story
2845,9780575075597,0575075597,Replay,Ken Grimwood,Fantasy,http://books.google.com/books/content?id=9vmNP...,At forty-three Jeff Winston is tired of his lo...,2005.0,4.16,272.0,412.0,117,Replay,9780575075597 At forty-three Jeff Winston is t...,This is a fictional story
2860,9780590254762,0590254766,"The lion, the witch and the wardrobe",Clive Staples Lewis,Fantasy,NaN,Four English school children enter the magic l...,1995.0,4.21,189.0,860.0,35,"The lion, the witch and the wardrobe",9780590254762 Four English school children ent...,This is a fictional story
3288,9780739423851,0739423851,Wizard's Castle,Diana Wynne Jones,Fantasy,http://books.google.com/books/content?id=hB7hA...,Howl's moving castle - Eldest of three sisters...,2002.0,4.44,376.0,439.0,90,Wizard's Castle,9780739423851 Howl's moving castle - Eldest of...,This is a fictional story
3289,9780739439708,0739439707,Time Quartet,Madeleine L'Engle,Science fiction,NaN,"Blending magic with quantum physics, Madeleine...",2003.0,4.35,646.0,165.0,38,Time Quartet,9780739439708 Blending magic with quantum phys...,This is a fictional story
3563,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,32,"20,000 Leagues Under the Sea",9780760728505 Retells the adventures of a Fren...,This is a fictional story
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,158,The Voyage of the Jerle Shannara Trilogy,9781416502043 When the body of a half-drowned ...,This is a fictional story
4979,9781841494081,1841494089,The Darkness that Comes Before,R. Scott Bakker,Fantasy,http://books.google.com/books/content?id=BG8qG...,A score of centuries has passed since the Firs...,2005.0,3.79,638.0,317.0,167,The Darkness that Comes Before,9781841494081 A score of centuries has passed ...,This is a fictional story
5040,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,109,Use of Weapons,9781857231359 The man known as Cheradenine Zak...,This is a fictional story
5057,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,80,The Gods Themselves,"9781857989342 In the year 2100, mankind on Ear...",This is a fictional story

In [174]:
books.to_csv("books_with_categories.csv", index=False)